### PR TITLE
Add network config and Degenicus as addStrategy listener

### PR DESCRIPTION
**Pull request by Kquach12**

### CODE REVIEW

**Comment by Kquach12** [comment]
yarn build --network optimism
yarn build --network fantom

These are the commands we'll run to flip between each chain before deploying. I believe we will need to specify which subgraph we're deploying too for each chain as well.

graph deploy --product hosted-service byte-masons/multi-strategy-vaults-optimism
graph deploy --product hosted-service byte-masons/multi-strategy-vaults-fantom

**Review by 0xulver — COMMENTED** [review]
The commands need to be added to the package.json file and it would also be good to have it in documentation so it is clear how to use this.

We could have different commands like deploy-fantom, deploy-optimism.

Has this been tested at all to make sure it works?

**Comment by Kquach12** [comment]
Commands have been added as well as a README. Let me know if it's clear or not and I can adjust it.

I tested out each new command on my personal subgraph and everything seems to be working (it's still syncing, but no errors so far). I've only tested the build commands on this repo, not the deploy commands yet.

**Review by 0xulver — APPROVED** [review]
Looks good

**Pull request merged**
